apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mysql-1-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /mysql-1-data
