apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-1
spec:
  selector:
    matchLabels:
      app: mysql1
  replicas: 1
  template:
    metadata:
      name: mysql-1-pod
      labels:
        app: mysql1
    spec:
      containers:
        - image: mysql:latest
          name: mysql-cont-1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: USER_DATABASE

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: USER_NAME

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: USER_PASSWORD

          volumeMounts:
            - name: mysql-vol-claim
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-vol-claim
          persistentVolumeClaim:
            claimName: mysql-pvc-1
              