apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-2-deploy
  labels:
    app: wordpress-2
spec:
  selector:
    matchLabels:
      app: wb2
  replicas: 3
  template:
    metadata:
      name: wordpress-2-pod
      labels:  
        app: wb2
    spec:
      containers:
        - image: wordpress:latest
          name: wordpress-2-cont
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service-2

            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: wordpress-configmap
                  key: WORDPRESS_DB_USER

            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wordpress-configmap
                  key: WORDPRESS_DB_NAME


            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: WORDPRESS_DB_PASSWORD
